# Configuration file for model architecture `SCINet`
model_params:
    st_params:
        n_stacks: 2
        n_levels: 3
        n_decoder_layer: 2
        h_ratio: 8
        kernel_size: 5
        groups: 321
        dropout: 0
        INN: True
        positional_ecoding: False
        dataset_name: electricity
    loss_params:
        single_step: 1
        lastWeight: 1.0
        criterion: smooth_l1_loss
    in_len: 168
    out_len: 3
    n_series: 321

fit_params: