# Configuration file for model architecture `SCINet`
model_params:
    net_params:
        dataset_name: pems_bay
        t_window: 12
        n_series: 325
        num_stacks: 1
        num_levels: 2
        num_decoder_layer: 2
        output_len: 12
        concat_len: 0
        hid_size: 0.0625
        kernel_size: 5
        groups: 1
        dropout: 0.25
        INN: True
        single_step_output_One: 0
        positionalEcoding: True
        RIN: False
    loss_params:
        single_step: 0
        lastWeight: 1.0
        criterion: l1

fit_params: