# Configuration file for model architecture `SCINet`
model_params:
    st_params:
        n_stacks: 2
        n_levels: 4
        n_decoder_layer: 1
        h_ratio: 1
        kernel_size: 5
        groups: 1
        dropout: 0.25
        INN: True
        positional_ecoding: False
        dataset_name: solar_energy
    loss_params:
        single_step: 0
        lastWeight: 0.5
        criterion: smooth_l1_loss
    in_len: 160
    out_len: 3
    n_series: 137

fit_params: