# Configuration file for model architecture `SCINet`
model_params:
    st_params:
        n_stacks: 1
        n_levels: 3
        n_decoder_layer: 2
        h_ratio: 0.125
        kernel_size: 5
        groups: 1
        dropout: 0.5
        INN: True
        positional_ecoding: False
        dataset_name: exchange_rate
    loss_params:
        single_step: 0
        lastWeight: 0.5
        criterion: smooth_l1_loss
    in_len: 168
    out_len: 3
    n_series: 8

fit_params: