# Configuration file for model architecture `STGCN`
model_params:
    # Spatial/Temporal pattern extractor
    st_params:
        Kt: 3
        Ks: 3
        blocks: [[1], [64, 16, 64], [64, 16, 64], [128, 128], [12]]
        n_series: 207
        t_window: 12
        act_func: 'glu'
        graph_conv_type: 'cheb_graph_conv'
        bias: True
        dropout: 0.5
        
    device: 'cuda:0'      
    out_dim: 12

fit_params: