adj_reg: null
clip_grad_norm: 5
dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: true
device: cuda:0
epochs: 100
es:
  mode: min
  patience: 50
evaluator:
  eval_metrics:
  - mmae
  - mrmse
  - mmape
  horiz_cuts:
  - 3
  - 6
  - 12
loss_fn:
  cl: null
  custom: false
  mtk: null
  name: ml1
  rescale: true
model_ckpt:
  best_ckpt_mid: last
  ckpt_metric: null
  ckpt_mode: null
seed: 3566295508
solver:
  lr_skd:
    T_max: null
    eta_min: null
    factor: 0.5
    gamma: 0.1
    milestones:
    - 20
    - 30
    - 40
    - 50
    mode: min
    name: multistep
    patience: 5
    step_per_batch: false
  optimizer:
    amsgrad: true
    beta1: 0.9
    beta2: 0.999
    dampening: null
    eps: 1e-3
    lr: 0.01
    lr_decay: null
    momentum: null
    name: adam
    nesterov: null
    rho: null
    weight_decay: 0
