# Configuration file for model architecture `STSGCN`
model_params:
    # Spatial/Temporal pattern extractor
    st_params:
        n_series: 207
        t_window: 12
        in_channels: 1
        hid_dim: 64
        act_func: "GLU"
        filters: [[64, 64, 64],
                  [64, 64, 64],
                  [64, 64, 64],
                  [64, 64, 64]]
    # hyperparameters of Spatial-Temporal embedding
    emb_params:
        temporal_bool: True
        spatial_bool: True
    
    device: "cuda:0"
    out_dim: 12

fit_params: