# Configuration for data processing
# ==Metadata==
dataset_name: electricity

# ==Data Processing==
dp:
    # Time stamp encoder
    time_enc:
      add_tid: False
      add_diw: False
      n_tids: 24
      max_norm: False

    # Holdout (fixed)
    holdout_ratio: 0.2

    # Scaling
    scaling: max

    # Priori graph structure
    priori_gs:
        type: null
        k: null

    # Auxiliary data
    aux_data:
        file_path: null

# ==CV Scheme==
cv:
    scheme: tssplit
    n_folds: 1
    train_ratio: 0.75
    val_ratio: 0.25

# ==Dataset==
dataset:
    t_window: 168
    horizon: 6
    n_tids: 24         # Number of time slots in one day
    multi_step: True
    day_window: null
    week_window: null
    num_of_day: null
    num_of_week: null
