# Configuration file for model architecture `MTGNN`
model_params:
    # Graph Learning Layer
    gsl_params:
        n_series: 321
        node_emb_dim: 40
        alpha: 3
        k: 20
    # Spatial/Temporal Convolution Module
    st_params:
        n_layers: 5
        tcn_in_dim: 16
        gcn_in_dim: 16
        kernel_size: [2, 3, 6, 7]
        dilation_exponential: 2
        gcn_depth: 2
        beta: 0.05
        dropout: 0.3
        ln_affine: False 
    in_dim: 1
    skip_dim: 32
    end_dim: 64
    in_len: 168
    out_len: 1

fit_params: