# Configuration file for model architecture `TPA-LSTM`
model_params:
    # Spatial/Temporal pattern extractor
    st_params:
        lin_h_dim: 862
        rnn_h_dim: 45
        rnn_n_layers: 3
        rnn_dropout: 0
        cnn_h_dim: 32
        ar_window: 24
    in_len: 168
    out_len: 1
    n_series: 862

fit_params: