# Configuration file for model architecture `MegaCRN`
model_params:
    # Spatial/Temporal pattern extractor
    st_params:
        n_series: 883
        enc_in_dim: 1
        dec_in_dim: 2
        out_dim: 1
        rnn_units: 64
        num_layers: 1
        cheb_k: 3
        cl_decay_steps: 2000
        use_curriculum_learning: True
    mem_params:
        mem_num: 20
        mem_dim: 64
    loss_params:
        lamb: 0.01
        lamb1: 0.01
    out_len: 12

fit_params: