# Configuration file for model architecture `GWNet`
model_params:
    # Spatial/Temporal Convolution Module
    st_params:
        blocks: 4
        layers: 2
        dropout: 0.3
        # Spatial
        addaptadj: True
        adaptive_init: null
        randomadj: True
        adaptive_only: False
        gcn_true: True
        gcn_depth: 2
        n_series: 207
        # Temporal
        dilation_exponential: 2
        kernel_size: 2
        t_window: 12
    # input/output channels
    ch_params:
        dilation_channels: 32
        residual_channels: 32
        skip_channels: 256
        end_channels: 512
        in_channels: 2
    out_dim: 12
    device: 'cuda:0'

fit_params: